### ISSUE TITLE
Wrong domain blocked - europarl.europa.eu

### ISSUE THREAD

**Issue by ghost** [divestedcg/Simple_Hosts_Merger#2]
Hello,

The list https://divested.dev/hosts-domains-wildcards is blocking the `europarl.europa.eu`, which is the legitimate domain of the European Parliament. I could not find from which blocklist the domain comes, so probably it got caught in the process of extrapolating the domain from a specific rule.

**Comment by SkewedZeppelin** [comment]
I've exempted this and a few others for next list update, thank you for the report.

**Comment by ghost** [comment]
Thank you @SkewedZeppelin! I also noticed that `trenitalia.com`, the legitimate website of the Italian train operator, gets blocked.

**Comment by SkewedZeppelin** [comment]
Thanks, fixed for next list update.
